/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BudgetBar: typeof import('./src/components/BudgetBar.vue')['default']
    CustomTabbar: typeof import('./src/components/CustomTabbar.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdDatetimePickerView: typeof import('@wot-ui/ui/components/wd-datetime-picker-view/wd-datetime-picker-view.vue')['default']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['default']
    WdPickerView: typeof import('@wot-ui/ui/components/wd-picker-view/wd-picker-view.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdSwipeAction: typeof import('@wot-ui/ui/components/wd-swipe-action/wd-swipe-action.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['default']
    YearMonthPicker: typeof import('./src/components/YearMonthPicker.vue')['default']
  }
}
