export interface ThemePreset {
  name: string
  label: string
  colors: Record<string, string>
}

export const themePresets: ThemePreset[] = [
  {
    name: 'teal',
    label: '稳重蓝绿',
    colors: {
      '--color-primary': '#0D9488',
      '--color-primary-light': '#E6F7F5',
      '--color-primary-dark': '#0B7A70',
      '--color-bg-page': '#F5F7FA',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-input': '#F8FAFC',
      '--color-text-primary': '#1E293B',
      '--color-text-secondary': '#94A3B8',
      '--color-text-tertiary': '#CBD5E1',
      '--color-text-inverse': '#FFFFFF',
      '--color-border': '#E2E8F0',
      '--color-border-light': '#F1F5F9',
      '--color-success': '#10B981',
      '--color-danger': '#EF4444',
      '--color-warning': '#F59E0B',
      '--color-wechat': '#07C160',
      '--color-info': '#3B82F6',
      '--color-mask': 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    name: 'blue',
    label: '深邃蓝',
    colors: {
      '--color-primary': '#2563EB',
      '--color-primary-light': '#EFF6FF',
      '--color-primary-dark': '#1D4ED8',
      '--color-bg-page': '#F8FAFC',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-input': '#F8FAFC',
      '--color-text-primary': '#1E293B',
      '--color-text-secondary': '#94A3B8',
      '--color-text-tertiary': '#CBD5E1',
      '--color-text-inverse': '#FFFFFF',
      '--color-border': '#E2E8F0',
      '--color-border-light': '#F1F5F9',
      '--color-success': '#10B981',
      '--color-danger': '#EF4444',
      '--color-warning': '#F59E0B',
      '--color-wechat': '#07C160',
      '--color-info': '#3B82F6',
      '--color-mask': 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    name: 'amber',
    label: '暖琥珀',
    colors: {
      '--color-primary': '#D97706',
      '--color-primary-light': '#FFF7ED',
      '--color-primary-dark': '#B45309',
      '--color-bg-page': '#FFFBEB',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-input': '#F8FAFC',
      '--color-text-primary': '#1E293B',
      '--color-text-secondary': '#94A3B8',
      '--color-text-tertiary': '#CBD5E1',
      '--color-text-inverse': '#FFFFFF',
      '--color-border': '#E2E8F0',
      '--color-border-light': '#F1F5F9',
      '--color-success': '#10B981',
      '--color-danger': '#EF4444',
      '--color-warning': '#F59E0B',
      '--color-wechat': '#07C160',
      '--color-info': '#3B82F6',
      '--color-mask': 'rgba(0, 0, 0, 0.5)',
    },
  },
]

export const themeColorLabels: Record<string, string> = {
  '--color-primary': '主色',
  '--color-primary-light': '主色浅底',
  '--color-primary-dark': '主色深色',
  '--color-bg-page': '页面背景',
  '--color-bg-card': '卡片背景',
  '--color-bg-input': '输入框背景',
  '--color-text-primary': '主文字',
  '--color-text-secondary': '次文字',
  '--color-text-tertiary': '三级文字',
  '--color-text-inverse': '反色文字',
  '--color-border': '边框',
  '--color-border-light': '浅边框',
  '--color-success': '成功色',
  '--color-danger': '危险色',
  '--color-warning': '警告色',
  '--color-wechat': '微信色',
  '--color-info': '信息色',
  '--color-mask': '遮罩',
}
